language: node_js

node_js:
  - 10

sudo: required

services:
  - docker

stages:
  - Tests
  - Deploy

before_install:
  - yarn install
  # - docker network create network-api

  # install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh

  # login to docker registries (dockerhub + heroku)
  - echo docker login -u "$DOCKERUSERNAME" -p "$DOCKERPASSWORD"
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" registry.heroku.com

jobs:
  include:
    - stage: "Tests"
      name: "Tests"
      script:
#       - yarn run test -u --coverage

        # run lint and tests
        - yarn quality-check
        - ./node_modules/.bin/codecov -t ${CODECOV_TOKEN}
    - stage: "Deploy"
      name: "Deploy"
      if: branch = devel
      script:
        - docker build -t gymnasteg2019/frontend:homolog .
        - docker tag gymnasteg2019/frontend:homolog registry.heroku.com/$HEROKU_APP_NAME/web
        - docker push gymnasteg2019/frontend:homolog
        - docker push registry.heroku.com/$HEROKU_APP_NAME/web
        - heroku container:release web --app $HEROKU_APP_NAME
        # - docker run -e CI=true frontend yarn run test
